config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :player do
    resources :tournaments, only: :index
    resources :availabilities, only: [:index, :create, :update, :destroy]
    resources :convocations, only: [:index] do
      member do
        post 'refuse'
        post 'accept'
      end
    end
  end

  resources :tournaments, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      post "convocations/grouped_send", to: "convocations#grouped_send"
      resources :matches, only: [:index, :create]
      resources :registrations, only: [:index, :new, :create]
    end
  end
  resources :registrations, only: [:edit, :update, :destroy]
  resources :matches, only: [:update, :destroy]
  resources :convocations, only: [] do
    member do
      post 'accept'
      post 'refuse'
      post 'unique_send'
    end
  end
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :supervisor, class_name: 'User'
  has_many :registrations
  has_many :matches
  has_many :users, through: :registrations
  has_many :convocations, through: :matches

  validates :name, presence: true
  validates :city, presence: true
  validates :courts_number, numericality: { only_integer: true, greater_than: 0 }
  validates :match_duration, numericality: { only_integer: true }
  validates :begin_at, presence: true
  validates :end_at, presence: true

  mount_uploader :photo, PhotoUploader

  def send_convocations
    self.convocations.each do |convocation|
      convocation.pending! if convocation.to_be_sent? && !convocation.match.begin_at.nil? && !convocation.match.begin_at.nil?
    end
  end
end

app/controllers/player/tournaments_controller.rb
class Player::TournamentsController < ApplicationController
  def index
    @user = current_user

    @registrations = @user.registrations
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournaments, only: [:show, :edit, :update]
  def index
    @user = current_user
    @tournaments = @user.tournaments
    @tournament = Tournament.new

  end

  def show
   @match = Match.new
   if params[:date].present?
    @date = DateTime.parse(params[:date])
  else
   @date = DateTime.now
  end
end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = Tournament.new(tournament_params)
    @tournament.supervisor = current_user
    if @tournament.save
      flash[:notice] = "Nouveau tournoi créé !"

      respond_to do |format|
        format.html { redirect_to tournaments_path }
        format.js # render create.js.erb
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def edit
  end

  def update
    if @tournament.update(tournament_params)
      redirect_to tournaments_path
    else
      render :edit
    end
  end

  private

  def set_tournaments
   @tournament = Tournament.find(params[:id])
  end

  def tournament_params
    params.require(:tournament).permit([:name, :city, :courts_number, :match_duration, :begin_at, :end_at, :user, :photo, :file])
  end
end

app/views/tournaments/_form.html.erb
<div class="container datepicker">
  <%= simple_form_for tournament, remote: true do |form|%>
    <%= form.input :name, label: "Nom" %>
    <%= form.input :city, input_html: {id:'city_form', class: "autocomplete"}, label: "Ville", as: :string %>
    <%= form.input :courts_number, label: "Nombre de courts", min_max: 1 %>
    <%= form.input :match_duration, label: "Durée de matchs par défaut (en minutes)", default: 90 %>
    <%= form.input :begin_at, input_html: { id:'start_date' }, label: "Début", as: :string %>
    <%= form.input :end_at, input_html: { id:'end_date'}, label: "Fin", as: :string %>
    <%= form.input :photo %>
    <%= form.input :photo_cache, as: :hidden %>


    <%= form.submit "Valider", method: :post, class: "btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/tournaments/_tournament.html.erb
<div class="col-xs-12 col-sm-4">
  <div class="card mb-2" style="width: 18rem; align-items: center;">
    <%= cl_image_tag tournament.photo, id: "logo", width:250, height: 250 %>
    <div class="card-body">
      <h5 class="card-title"><%= tournament.name %></h5>
      <p class="card-text"><%= tournament.city %></p>
      <p class="card-date">Du <%= tournament.begin_at.strftime("%d/%m/%Y") %> au <%= tournament.end_at.strftime("%d/%m/%Y") %></p>
      <% if current_user.supervisor  %>
        <%= link_to "Gestion des matchs", registrations_path(tournament), class: "btn btn-outline-secondary btn-block"%>
        <%= link_to "Modifier", edit_tournament_path(tournament), class: "btn btn-outline-secondary btn-block"%>
        <% end  %>
    </div>
  </div>
</div>

app/views/tournaments/_tournament_card.html.erb
<div class="card mb-2" style="width: 18rem;">
  <div class="card-header">
  <%= image_tag tournament.photo_url, id: "logo", width:250, height: 250 %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= tournament.name %></h5>
    <p class="card-title">à <%= tournament.city %></p>
    <p class="card-date">Du <%= tournament.begin_at.strftime("%d/%m/%Y") %> au <%= tournament.end_at.strftime("%d/%m/%Y") %></p>
    <% if current_user.supervisor  %>
      <%= link_to "Gestion des matchs", registrations_path(tournament), class: "btn btn-outline-secondary btn-block"%>
      <%= link_to "Modifier", edit_tournament_path(tournament), class: "btn btn-outline-secondary btn-block"%>
      <% end  %>
  </div>
</div>

app/views/tournaments/create.js.erb
<% if @tournament.errors.any? %>
  // re render form
  document.getElementById('new-tournament').innerHTML = "<%= j render 'form', tournament: @tournament %>";
<% else %>
  // close modal
  closeBootstrapModal('#create_tournament');
  document.getElementById('flashes').innerHTML = '<%= j render "shared/flashes" %>'
  // re render list of tournaments cards
  document.getElementById('tournament-cards').insertAdjacentHTML('beforeend', "<%= j render 'tournaments/tournament', tournament: @tournament %>");
<% end %>

app/views/tournaments/edit.html.erb
<div class="container py-5">
  <h2> Mise à jour du tournoi</h2>
  <div class="row">
    <div class="container datepicker">
      <%= simple_form_for @tournament do |form|%>
        <%= form.input :name, label: "Nom" %>
        <%= form.input :city, input_html: {id:'city_form', class: "autocomplete"}, label: "Ville", as: :string %>
        <%= form.input :courts_number, label: "Nombre de courts" %>
        <%= form.input :begin_at, input_html: { id:'start_date' }, label: "Début", as: :string %>
        <%= form.input :end_at, input_html: { id:'end_date'}, label: "Fin", as: :string %>
        <%= form.submit "Valider", method: :post, class: "btn btn-outline-secondary" %>
      <% end %>
    </div>


  </div>
</div>

app/views/tournaments/index.html.erb
  <div class="container py-2">

    <div class="d-flex flex-row-reverse">
      <div class="p-2">
        <button type="button" class="btn btn-outline-secondary" style="margin-top: 25px; margin-bottom: 25px" data-toggle="modal" data-target="#create_tournament">
          Nouveau tournoi
        </button>
      </div>
    </div>

    <div class="row py-2" id="tournament-cards">
      <%= render collection: @tournaments, partial: "tournaments/tournament" %>
    </div>
  </div>



<!-- Modal -->
<div class="modal fade" id="create_tournament" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nouveau tournoi</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="new-tournament">
        <%= render 'form', tournament: @tournament %>
      </div>
    </div>
  </div>
</div>

app/views/tournaments/new.html.erb
<div class="container py-5">
  <h2> Création d'un tournoi</h2>
  <div class="row">
      <%= render 'form', tournament: @tournament %>
  </div>
</div>

app/views/tournaments/show.html.erb
<%= render 'shared/tabs' %>
<div class="container-fluid px-5">
    <div class="text-center py-3">
      <h2><%= @tournament.name %> / Matchs du jour</h2>
    </div>
    <div class="d-flex justify-content-center align-items-center mb-3">
      <%= link_to "Précédent  <  ", tournament_path(@tournament, date: @date - 1.days), class: 'text-secondary mr-5'%>
      <h3> <%= @date.strftime("%d.%m.%Y") %></h3>
      <%= link_to "  >  Suivant", tournament_path(@tournament, date: @date + 1.days), class: 'text-secondary ml-5' %>
    </div>

    <div class="row">
      <div class="col-md-10">
        <div class="container-fluid">
          <div class="row">
            <div class="col-2"></div>
            <% (1..5).each do |col| %>
              <div class="col-2 text-center">
                Court <%= col %>
              </div>
            <% end %>
          </div>
          <% (9..22).each do |hour|%>
            <div class="row" style="border-top: 1px solid #CCC; height:80px">
              <div class="col-2">
                <%= hour %>:00
              </div>
              <% (1..5).each do |court| %>
                <div class="col-2 dropable" data-date="<%= @date.change(hour: hour) %>" data-court=<%= court %>>
                  <% @tournament.matches.where(court:court, begin_at: @date.change(hour: hour)).each do |match| %>
                    <%= render "shared/card_match", match: match %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-2">
        <%= link_to "Envoyer les convocations", convocations_grouped_send_tournament_path(@tournament, date: params[:date]), method: :post, class: "btn btn-outline-success btn-block" %>
        <button type="button" class="btn btn-outline-secondary btn-block" style="margin-top: 25px; margin-bottom: 25px" data-toggle="modal" data-target="#create_match">Nouveau match
        </button>
        <div class="border-light shadow">
        <div class="dropable">
          <p class="text-center">-Matchs à placer-<p>
            <% @tournament.matches.for_index.order(created_at: :desc).each do |match| %>
              <%= render "shared/card_match", match: match %>
            <% end %>
        </div>
        </div>
    </div>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="create_match" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nouveau match</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'shared/match_form' %>
      </div>
    </div>
  </div>
</div>

app/views/tournaments/show.js.erb
// var matchCard = document.getElementById("card-<%=@match.id%>");
// var iconCard = matchCard.querySelector(".far");

// iconCard.classList ="";
// iconCard.classList.add("far", "fa-envelope", "orange-color","pl-2");