config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :player do
    resources :tournaments, only: :index
    resources :availabilities, only: [:index, :create, :update, :destroy]
    resources :convocations, only: [:index] do
      member do
        post 'refuse'
        post 'accept'
      end
    end
  end

  resources :tournaments, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      post "convocations/grouped_send", to: "convocations#grouped_send"
      resources :matches, only: [:index, :create]
      resources :registrations, only: [:index, :new, :create]
    end
  end
  resources :registrations, only: [:edit, :update, :destroy]
  resources :matches, only: [:update, :destroy]
  resources :convocations, only: [] do
    member do
      post 'accept'
      post 'refuse'
      post 'unique_send'
    end
  end
end

app/views/shared/_card_convocation.html.erb
<div class="card border-secondary mb-3 mx-3 pb-3" id="card-<%=convocation.id %>">
  <div class="card-header d-flex justify-content-between">
    <%= convocation.match.tournament.name %>
    <% if convocation.status.to_s == "refused" %>
      <i class="far fa-times-circle red-color size-icon"></i>
    <% elsif convocation.status.to_s == "pending"  %>
      <i class="far fa-clock orange-color size-icon"></i>
    <% else %>
      <i class="far fa-check-circle green-color size-icon"></i>
    <% end %>
  </div>
  <div class="card-body text-secondary">
    <p class="card-text">Le <%= convocation.match.begin_at.strftime("%d/%m/%Y à %I:%M%p") %> </p>
  </div>
  <% if convocation.pending? %>
  <div class="action-buttons">
    <div class="d-flex justify-content-around">
      <button type="button" class="btn btn-success btn-sm" id="accept_button"><%= link_to "J'accepte", accept_player_convocation_path(convocation), method: :post, remote: true %></button>
      <button type="button" class="btn btn-danger btn-sm" id="refuse_button"><%= link_to "Je refuse", refuse_player_convocation_path(convocation), method: :post, remote: true %></button>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_card_match.html.erb
<div class="card w-100 my-1 shadow-sm" style="background: #06AED3" data-match-id="<%= match.id %>" id="card-<%= match.id %>"  >
  <% match.convocations.each do |convocation| %>
    <div class="card-body text-white" >
      <div class="card-text d-flex justify-content-between" style="opacity: 1">
        <div class="w-70" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-weight: bolder; color: white; ">
          <%= convocation.user.first_name %> <%= convocation.user.last_name %> (#<%= convocation.registration.category.first(3) %>)
        </div>
        <% if convocation.refused? %>
          <i class="far fa-times-circle red-color pl-2 font-weight-bold"></i>
        <% elsif convocation.pending? %>
          <i class="far fa-clock orange-color pl-2 font-weight-bold"></i>
        <% elsif convocation.accepted?%>
          <i class="far fa-check-circle green-color pl-2 font-weight-bold"></i>
        <% elsif convocation.to_be_sent?%>
          <i class="far fa-envelope orange-color pl-2 font-weight-bold"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<!-- Modal -->
<div class="modal fade" id="maj_match" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modifier les paramètres du match</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for([match]) do |f| %>
          <div class="form-inputs">
            <%= f.input :begin_at %>
          </div>
      </div>
      <div class="modal-footer">
        <div class="form-actions">
          <%= f.button :submit, "Mettre à jour", method: :patch, class:'btn btn-warning'  %>
          <%= link_to "Supprimer", match_path(match), method: :delete, class:'btn btn-secondary'%>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_match_form.html.erb
<div>
  <h4>Nouveau match</h4>
  <%= simple_form_for([@match]) do |f| %>
    <%= f.simple_fields_for :convocations, Convocation.new do |convocation| %>
      <%= convocation.input :registration_id, label: "Joueurs", collection: @tournament.registrations, as: :select, id: 'convocation1' %>
    <% end %>
    <%= f.simple_fields_for :convocations, Convocation.new do |convocation| %>
      <%= convocation.input :registration_id, label: false, collection: @tournament.registrations, id: 'convocation2' %>
    <% end %>
<!--     <div class="form-inputs datepicker-match">
      <%= f.input :begin_at, label: "Date", input_html: { id:'match-time'}, as: :string %>
    </div> -->
    <div class="form-actions">
      <%= f.button :submit, "Créer", class: "btn btn-outline-secondary btn-block"  %>
    </div>
  <% end %>
</div>

app/views/shared/_matches_list.html.erb
<div class="card shadow my-3">
  <% @tournament.matches.for_index.order(created_at: :desc).each do |match| %>
    <%= render "shared/card_match", match: match %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <% if user_signed_in? %>
    <% if current_user.supervisor %>
      <%= link_to tournaments_path, class: "navbar-wagon-brand navbar-wagon-item navbar-wagon-link" do %>
      <%= image_tag "https://s1.qwant.com/thumbr/0x380/9/9/55f7baade4fc7b73e94047a5ee1fc5cb2d52a572b2df74128ba5071763b542/tennis-ball-clipart-red-11.png?u=http%3A%2F%2Fmoziru.com%2Fimages%2Ftennis-ball-clipart-red-11.png&q=0&b=1&p=0&a=1", height: 50 %>
      <% end %>
    <% else %>
      <%= link_to player_convocations_path, class: "navbar-wagon-brand navbar-wagon-item navbar-wagon-link" do %>
      <%= image_tag "https://s1.qwant.com/thumbr/0x380/9/9/55f7baade4fc7b73e94047a5ee1fc5cb2d52a572b2df74128ba5071763b542/tennis-ball-clipart-red-11.png?u=http%3A%2F%2Fmoziru.com%2Fimages%2Ftennis-ball-clipart-red-11.png&q=0&b=1&p=0&a=1", height: 50 %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://s1.qwant.com/thumbr/0x380/9/9/55f7baade4fc7b73e94047a5ee1fc5cb2d52a572b2df74128ba5071763b542/tennis-ball-clipart-red-11.png?u=http%3A%2F%2Fmoziru.com%2Fimages%2Ftennis-ball-clipart-red-11.png&q=0&b=1&p=0&a=1", height: 50 %>
    <% end %>
  <% end %>


  <!-- Title -->
  <div class="navbar-wagon-center ">
   <%= link_to root_path do %>
    <h3> Plan my play</h3>
   <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <div class="navbar-wagon-item">
      <% if user_signed_in? %>
        <div class="dropdown">
          <p class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
            <%= current_user.first_name%> <%= current_user.last_name.upcase %>
          </p>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Paramètres") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <%= link_to t(".sign_in", default: "Connexion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_player_availabilities_hover.html.erb
<div class="container">
  <div class="row" style="justify-content: space-between;">
    <p><%= registration.user.first_name %> <%= registration.user.last_name %> </p>
    <p><%= registration.user.club %></p>
    <p><%= registration.user.ranking %></p>
  </div>
  <% if registration.user.availabilities.empty? %>
    <p>Aucune disponibilité pour ce joueur</p>
  <% else %>
    <p>Disponibilités :</p>
    <ul>
    <% registration.user.availabilities.each do |availability| %>
      <div class="row" style="justify-content: center;">
        <p><%= availability.begin_at.strftime("Le  %d-%m  ") %><%= availability.begin_at.strftime(" de %I:%M  ") %><%= availability.end_at.strftime("  à %I:%M") %></p>
      </div>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_player_card.html.erb
<div class="card border-secondary mb-3">
  <div class="card-header d-flex justify-content-between">
      <%= registration.user.first_name.capitalize %>
      <%= registration.user.last_name.capitalize %>
  </div>
  <div class="card-body text-secondary">
    <span class="card-text"> Class. : <%= registration.user.ranking %></span>
    <br>
    <span> Club : <%= registration.user.club.capitalize %></span>
    <br>
    <span> Cat. : #<%= registration.category %></span>
  </div>
  <div class="player" data-id="<%= registration.id %>"> Ajouter </div>
</div>

app/views/shared/_tabs.html.erb
<% if user_signed_in? %>
  <% if current_user.supervisor %>
    <div class="container-fluid px-5">
<!--       <div class="row d-flex">
        <div class="col-md-8 offset-2"> -->
          <ul class="nav nav-tabs d-flex">
            <li class="nav-item flex-fill text-center">
              <%= link_to "Joueurs", registrations_path(@tournament), class: tab_classes(registrations_path(@tournament)) %>
            </li>
            <li class="nav-item flex-fill text-center">
              <%= link_to "Matchs", tournament_path(@tournament), class: tab_classes(tournament_path(@tournament)) %>
            </li>
          </ul>
<!--         </div>
      </div> -->
    </div>
  <% else %>
    <div class="container-fluid px-5">
        <ul class="nav nav-tabs d-flex">
          <li class="nav-item flex-fill text-center">
            <%= link_to "Mes convocations",  player_convocations_path, class: tab_classes(player_convocations_path) %>
          </li>
          <li class="nav-item flex-fill text-center">
            <%= link_to "Mes tournois",  player_tournaments_path, class: tab_classes(player_tournaments_path) %>
          </li>
          <li class="nav-item flex-fill text-center">
            <%= link_to "Mes disponibilités",  player_availabilities_path, class: tab_classes(player_availabilities_path) %>
          </li>
        </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_tournament_card.html.erb
<div class="card mb-2" style="width: 18rem;">
  <div class="card-header">
  <%= cl_image_tag tournament.photo, id: "logo", width:250, height: 250 %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= tournament.name %></h5>
    <p class="card-title">à <%= tournament.city %></p>
    <p class="card-date">Du <%= tournament.begin_at.strftime("%d/%m/%Y") %> au <%= tournament.end_at.strftime("%d/%m/%Y") %></p>
    <% if current_user.supervisor  %>
      <%= link_to "Gestion des matchs", registrations_path(tournament), class: "btn btn-outline-secondary btn-block"%>
      <%= link_to "Modifier", edit_tournament_path(tournament), class: "btn btn-outline-secondary btn-block"%>
      <% end  %>
  </div>
</div>