config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :player do
    resources :tournaments, only: :index
    resources :availabilities, only: [:index, :create, :update, :destroy]
    resources :convocations, only: [:index] do
      member do
        post 'refuse'
        post 'accept'
      end
    end
  end

  resources :tournaments, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      post "convocations/grouped_send", to: "convocations#grouped_send"
      resources :matches, only: [:index, :create]
      resources :registrations, only: [:index, :new, :create]
    end
  end
  resources :registrations, only: [:edit, :update, :destroy]
  resources :matches, only: [:update, :destroy]
  resources :convocations, only: [] do
    member do
      post 'accept'
      post 'refuse'
      post 'unique_send'
    end
  end
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user
end

app/controllers/player/availabilities_controller.rb
class Player::AvailabilitiesController < ApplicationController
before_action :set_availability, only: [:update, :destroy]

  def index
    @user = current_user
    @availabilities = @user.availabilities
    @availability = Availability.new
  end

  def create
    @availability = Availability.new(params_availability)
    @availability.end_at = @availability.end_at.change(day: @availability.begin_at.day, month: @availability.begin_at.month, year: @availability.begin_at.year)

    @availability.user = current_user
    if @availability.save
      redirect_to player_availabilities_path
    else
      render :index
    end
  end

  def update
    @availability.update(params_availability)
    redirect_to player_availabilities_path
  end

  def destroy
    @availability.destroy
    redirect_to player_availabilities_path
  end

  private

  def set_availability
    @availability = Availability.find(params[:id])
  end

  def params_availability
    params.require(:availability).permit(:begin_at, :end_at, :user_id)
  end
end

app/controllers/player/convocations_controller.rb
class Player::ConvocationsController < ApplicationController

  before_action :set_convocation, only: [:accept, :refuse]

  def index
    @user = current_user
    @pending_convocations = @user.convocations.pending_ones
    @current_convocations = @user.convocations.current_ones
    respond_to do |format|
        format.html
        format.js
    end
  end

  def accept
    @convocation.accepted!
  end

  def refuse
    @convocation.refused!
  end

  private

  def set_convocation
    @convocation = Convocation.find(params[:id])
  end
end

app/controllers/player/tournaments_controller.rb
class Player::TournamentsController < ApplicationController
  def index
    @user = current_user

    @registrations = @user.registrations
  end
end

app/views/player/availabilities/index.html.erb
<%= render 'shared/tabs' %>
<%= render 'shared/flashes' %>

<div class="container py-4">
  <div class="row  border-dark border-bottom">
    <div class="newdispo">
      <h4 >Ajouter un nouveau créneau</h4>
    </div>
  </div>
  <div class="row my-3">
    <%= simple_form_for [:player, @availability], wrapper: :inline_form, html: { class: 'form-inline my-3' }  do |f| %>
      <%= f.input_field :begin_at, class: "form-control mx-2" %> jusqu'à
      <%= f.input_field :end_at, discard_day: true, discard_month: true, discard_year: true, class: "form-control mx-2" %>
      <%= f.submit "Créer", class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
  <div class="row border-dark border-bottom">
    <h4>Liste de mes disponibilités à venir</h4>
  </div>
  <div class="listedispo py-5">
    <% if @availabilities.empty? %>
      <div class="pt-3 ">
        N'ayant pas précisé vos disponibilités, le juge arbitre peut vous convoquer à toute heure de la journée !
      </div>
    <% else %>
      <div class="container">
        <% @availabilities.each do |availability| %>
          <div class="row justify-content-center py-2">
            <div class="card justify-content-center col-sm">
              <div>
                <span class="text-muted">Le</span>
                <strong><%= availability.begin_at.strftime("%d.%m.%Y")%></strong>
                <span class="text-muted"> de </span>
                <%= availability.begin_at.strftime("%HH%M")%>
                <%= availability.end_at.strftime("à %HH%M")%>
              </div>
            </div>
            <div class="col-sm">
              <%= link_to player_availability_path(availability), method: :delete, class: 'btn btn-light' do %>
                  <i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          </div>

        <% end %>
      </div>
    <% end %>
  </div>
</div>